repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.1.4
    hooks:
    - id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3  # pick whatever version you want
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782  # Use the ref you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.3
    hooks:
    -   id: bandit
